### ISSUE TITLE
Unable to get decrypted object that was encrypted through SES

### ISSUE THREAD

**Issue by abodnar** [gilt/node-s3-encryption-client#3]
I'm using SES to process emails and I save them encrypted to S3, but in my Lambda function, I'm not able to decrypt using the S3 encryption client you provide. The data of the object just comes back encrypted.

`        new s3EncryptClient.getObject({
            Bucket: S3Bucket,
            Key: S3Path + '/' + messageId,
            EncryptionContext: "KMS SES KEY"
`

I'm not sure what I need to do to get this to work. One thing I did notice in the metadata for the S3 Object is that I have x-amz-key-v2, but I noticed in your main.js, you have the metadataKmsKeyName as x-amz-key. If I change this, I get this error:

`  message: 'Expected params.EncryptionContext to be a map',`

Any help is appreciated.

**Comment by rlmartin** [comment]
Ok, looking at that quickly, it _might_ be an easy fix. I'll submit it in a new branch and if you could try/verify it, that would be appreciated.

**Comment by winzig** [comment]
Was anything ever discovered to resolve this issue, i.e. a new branch to test out? We're up the same creek.

**Comment by abodnar** [comment]
I ended up having to move the retrieval of the email to a Ruby program I wrote using Amazon's SDK.

**Comment by garthgoodson** [comment]
I wrote the following function to decode data encrypted from SES.  It seems to work.  It is based on the ruby code.  Hope it is helpful.

    /**
     * Decrypt s3 file data
     * @param  {object}   objectData result of s3 get call
     * @param  {Function} callback   function(err, data) returns error or decrypted data
     */
    function decrypt(objectData, callback) {
        var metadata = objectData.Metadata || {};
        var kmsKeyBase64 = metadata['x-amz-key-v2'];
        var iv = metadata['x-amz-iv'];
        var tagLen = (metadata['x-amz-tag-len'] || 0)/8;
        var algo = metadata['x-amz-cek-alg'];
        var encryptionContext = JSON.parse(metadata['x-amz-matdesc']);
    
        switch (algo) {
            case 'AES/GCM/NoPadding':
                algo = 'aes-256-gcm';
                break;
            case 'AES/CBC/PKCS5Padding':
                algo = 'aes-256-cbc';
                break;
            default:
                callback(new Error('Unsupported algorithm: ' + algo), null);
                return;
        }
    
        if (typeof (kmsKeyBase64) === 'undefined') {
            callback(new Error('Missing key in metadata'), null);
            return;
        }
    
        var kmsKeyBuffer = new Buffer(kmsKeyBase64, 'base64');
        kms.decrypt({
            CiphertextBlob: kmsKeyBuffer,
            EncryptionContext: encryptionContext
        }, function(err, kmsData) {
            if (err) {
                callback(err, null);
            } else {
                var data = objectData.Body.slice(0,-tagLen);
    
                var decipher = crypto.createDecipheriv(algo,
                                                       kmsData.Plaintext,
                                                       new Buffer(iv, 'base64'));
    
                if (tagLen !== 0) {
                    console.log(3);
                    var tag = objectData.Body.slice(-tagLen);
                    decipher.setAuthTag(tag);
                }
    
                var dec = decipher.update(data, 'binary', 'utf8');
                dec += decipher.final('utf8');
    
                console.log("Decoded:", dec);
                callback(null, dec);
            }
        });
    }

**Comment by jameskeesh** [comment]
@garthgoodson Hi Garth, do you plan to make an npm module of your code ? something like aws-ses-decrypt.
anyway, well done, you made my day :)

**Comment by dannylivington** [comment]
I'm getting the below error when trying to execute. I think its hitting on when performing "JSON.parse"? Any idea?

$node ses-decrypt.js

undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at decrypt (/usr/local/bin/node_modules/ses-decrypt.js:15:34)
    at Object.<anonymous> (/usr/local/bin/node_modules/ses-decrypt.js:75:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by johanbyren** [comment]
I got an error on the code from @garthgoodson. 
`Error: Invalid key length at new Decipheriv (crypto.js:267:16) at Object.createDecipheriv (crypto.js:627:10)`

But the solution for me was just to change `var decipher = crypto.createDecipheriv(algo,
                                                   kmsData.Plaintext,
                                                   new Buffer(iv, 'base64'));` to this instead: `const decipher = crypto.createDecipheriv( algo, res.Plaintext as Buffer, Buffer.from(iv, 'base64'));`

I think it was a good place to post here if some one more have the same problem. 
Thanks for the great code @garthgoodson, you saved me :)

**Comment by cleverbeagle** [comment]
Filling out @garthgoodson's code a little bit and updating to match latest JS/Node versions (I'm at 12.3.1 w/ this):

```
/* eslint-disable consistent-return */

const _ = require("lodash");
const AWS = require("aws-sdk");
const crypto = require("crypto");
const settings = require("../../settings");

AWS.config = new AWS.Config();

AWS.config.accessKeyId = settings.aws.akid;
AWS.config.secretAccessKey = settings.aws.sak;
AWS.config.region = "us-east-1";

AWS.config.update({
  signatureVersion: "v4"
});

const kms = new AWS.KMS();

let action;

const decryptMessage = (s3Object, decryptionData) => {
  try {
    return new Promise((resolve, reject) => {
      kms.decrypt(
        {
          CiphertextBlob: decryptionData.kmsKeyBuffer,
          EncryptionContext: decryptionData.encryptionContext
        },
        function(error, kmsResponse) {
          if (error) {
            reject(error);
          } else {
            const dataToDecrypt = s3Object.Body.slice(
              0,
              -decryptionData.tagLength
            );
            const decipher = crypto.createDecipheriv(
              decryptionData.algorithm,
              kmsResponse.Plaintext,
              Buffer.from(decryptionData.iv, "base64")
            );

            if (decryptionData.tagLength !== 0) {
              const tag = s3Object.Body.slice(-decryptionData.tagLength);
              decipher.setAuthTag(tag);
            }

            let decodedData = decipher.update(dataToDecrypt, "binary", "utf8");
            decodedData += decipher.final("utf8");
            resolve(decodedData);
          }
        }
      );
    });
  } catch (exception) {
    throw new Error(`[decryptS3Object.decryptMessage] ${exception.message}`);
  }
};

const determineAlgorithm = s3Object => {
  try {
    const algorithm = _.get(s3Object, "Metadata.x-amz-cek-alg", null);

    switch (algorithm) {
      case "AES/GCM/NoPadding":
        return "aes-256-gcm";
      case "AES/CBC/PKCS5Padding":
        return "aes-256-cbc";
      default:
        return { error: `Unrecognized algorithm: ${algorithm}.` };
    }
  } catch (exception) {
    throw new Error(
      `[decryptS3Object.determineAlgorithm] ${exception.message}`
    );
  }
};

const getDecryptionData = s3Object => {
  try {
    const metadata = _.get(s3Object, "Metadata", {});
    const kmsKeyBase64 = metadata["x-amz-key-v2"];
    const iv = metadata["x-amz-iv"];
    const tagLength = (metadata["x-amz-tag-len"] || 0) / 8;
    const algorithm = determineAlgorithm(s3Object);
    const kmsKeyBuffer = Buffer.from(kmsKeyBase64, "base64");
    const encryptionContext = JSON.parse(metadata["x-amz-matdesc"]);

    if (
      !kmsKeyBase64 ||
      !iv ||
      !tagLength ||
      !algorithm ||
      !kmsKeyBuffer ||
      !encryptionContext
    )
      return null;

    return {
      kmsKeyBase64,
      iv,
      tagLength,
      algorithm,
      kmsKeyBuffer,
      encryptionContext
    };
  } catch (exception) {
    throw new Error(`[decryptS3Object.getDecryptionData] ${exception.message}`);
  }
};

const validateOptions = options => {
  try {
    if (!options) throw new Error("options object is required.");
    if (!options.object) throw new Error("options.object is required.");
  } catch (exception) {
    throw new Error(`[decryptS3Object.validateOptions] ${exception.message}`);
  }
};

const decryptS3Object = async options => {
  try {
    validateOptions(options);
    const algorithm = determineAlgorithm(options.object);
    const decryptionData = getDecryptionData(options.object);

    if (typeof algorithm !== "object" && decryptionData) {
      // NOTE: We return an object with an error message if no match is found.
      const decryptedMessage = await decryptMessage(
        options.object,
        decryptionData
      );

      action.resolve(decryptedMessage);
    } else {
      throw new Error(algorithm.error);
    }
  } catch (exception) {
    action.reject(`[decryptS3Object] ${exception.message}`);
  }
};

module.exports = options =>
  new Promise((resolve, reject) => {
    action = { resolve, reject };
    decryptS3Object(options);
  });
```

Big thanks to @garthgoodson for this!
